version: '3'

services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=12345678
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data:
    driver: local
